"""The API serves the robustness leaderboard + reports (RR22)."""

from __future__ import annotations

from pathlib import Path

from starlette.testclient import TestClient

from axiom.api.app import create_app


def test_leaderboard_page_is_served():
    client = TestClient(create_app())
    resp = client.get("/static/robustness.html")
    assert resp.status_code == 200
    assert "Reward Robustness Leaderboard" in resp.text


def test_reports_are_served_when_present():
    if not Path("reports/robustness.json").exists():
        return  # generated by scripts/run_robustness.py; skip if absent
    client = TestClient(create_app())
    resp = client.get("/reports/robustness.json")
    assert resp.status_code == 200
    body = resp.json()
    assert "summary" in body and "by_task_version" in body["summary"]
